services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/data/postgres
    ports:
      - '5432:5432'